### ISSUE TITLE
Communication protocol

### ISSUE THREAD

**Issue by SrimantaBarua** [v-superuser/text-editor#7]
Note: Have a look at #6 too.

What will we need to send data for? I've come up with this list so far -
- [ ] Client -> Server : edits
- [ ] Client -> Server : cursor position
- [ ] Server -> Client : buffer updates
- [ ] Server -> Client : others' cursor positions
- [ ] Client -> Server : configuration
- [ ] Client -> Server : non-editing commands

Please do add to this list.

How are we going to do this? I'm thinking JSON.

```
{
    "type": "edit",
    "line": 20,
    "offset": 50,
    "string": "new string"
}
```
Something like this for 1., and so on for others.

Thoughts?
